print(bool("abc"))
print(bool(123))
print(bool(False))
print(bool(True))
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(["apple", "cherry", "banana"]))
print(bool(()))
print(bool({}))